import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Bebas_Neue, Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";

const bebasNeueHeading = Bebas_Neue({
   variable: "--font-heading",
   weight: ["400"],
   subsets: ["latin"],
});

const manrope = Manrope({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={cn(
            "h-full",
            "antialiased",
            "font-sans",
            manrope.variable,
            bebasNeueHeading.variable,
         )}
         suppressHydrationWarning
      >
         <body className="min-h-full flex flex-col">
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
